# -*- coding: utf-8 -*-
# Generated by Django 1.9.11 on 2017-09-22 21:46
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.FileField(blank=True, null=True, upload_to=b'')),
                ('nom_producto', models.CharField(max_length=200)),
                ('valor_producto', models.CharField(max_length=200)),
                ('fecha_vencimiento', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='TipoProducto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.FileField(blank=True, null=True, upload_to=b'')),
                ('nombre', models.CharField(max_length=200)),
                ('valor_tipo_producto', models.CharField(max_length=200)),
                ('fecha_vencimiento', models.CharField(max_length=200)),
            ],
        ),
        migrations.AddField(
            model_name='producto',
            name='tipo_producto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='productos.TipoProducto'),
        ),
    ]
