# -*- coding: utf-8 -*-
# Generated by Django 1.9.11 on 2017-09-26 20:19
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='producto',
            old_name='nom_producto',
            new_name='nombre',
        ),
    ]
